# Unique identifier for your project
sonar.projectKey=flask-docker-app

# Location of the source code (relative to this file)
sonar.sources=.

# Encoding of the source code
sonar.sourceEncoding=UTF-8

# Language-specific settings (Optional for Python/Flask)
sonar.python.version=3
